### ISSUE TITLE
Duplicate term

### ISSUE THREAD

**Issue by kjrawson** [DigitalTransgenderArchive/homosaurus_site#11]
There seems to be two LGBTQ+ Museums. Before deleting one, we wanted to make sure it was mapped to the other term so that some users didn't end up with a dead link.

Here's the one that should be no longer valid: https://homosaurus.org/v3/homoit0000907

And here's the one to preserve and map it to: https://homosaurus.org/v3/homoit0001030 

Thanks!

**Comment by scande3** [comment]
This should be completed.

**Comment by kjrawson** [comment]
Thank you!
