### ISSUE TITLE
Deletion of three terms

### ISSUE THREAD

**Issue by kjrawson** [DigitalTransgenderArchive/homosaurus_site#13]
The board would like to delete the following terms, though there no longer appears to be an option to do so:

https://homosaurus.org/v3/homoit0000397
https://homosaurus.org/v3/homoit0000586
https://homosaurus.org/v3/homoit0000615

Thanks!

**Comment by scande3** [comment]
This should be completed.

**Comment by kjrawson** [comment]
That's perfect––thanks so much for adding the notice!
