### ISSUE TITLE
Consolidating Two Terms

### ISSUE THREAD

**Issue by rolesc** [DigitalTransgenderArchive/homosaurus_site#17]
As part of our work restructuring disabilities-related terms in the Homosaurus, the board approved replacing the two existing terms [LGBTQ+ people with physical disabilities](https://homosaurus.org/v3/homoit0000916) and [LGBTQ+ people with visual disabilities](https://homosaurus.org/v3/homoit0000917) with the single term [LGBTQ+ disabled people](https://homosaurus.org/v3/homoit0001854). Can you consolidate those two terms into the new one so we can maintain a record of their past use?

**Comment by scande3** [comment]
This functionality should be available in the next editor update. Will update this ticket when that is so.

**Comment by scande3** [comment]
This should be available. For the moment, one goes to the term that should be the "primary term". On that term, one can then enter the identifier for the term that should now redirect to this term.

**Comment by rolesc** [comment]
Yes, it's working great! Thanks so much!
