### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by brimwats** [DigitalTransgenderArchive/homosaurus_site#22]
just opening an issue because editing isn't enabled yet (no worries!)

Can https://homosaurus.org/v3/homoit0000886 be updated from indigenous (lower i) to Indigenous (capital I)? Thanks so much!

**Comment by kjrawson** [comment]
Done!

**Comment by kjrawson** [comment]
@brimwats Feel free to close this ticket when you get a moment!
