### ISSUE TITLE
Alphabetize BTs, NTs, RTs in display

### ISSUE THREAD

**Issue by rolesc** [DigitalTransgenderArchive/homosaurus_site#25]
Hi Steven,

Is it possible to change the display for BTs, NTs, and RTs on the site so that they display alphabetically, even if they're not input alphabetically?

Thank you!

Cailin

**Comment by scande3** [comment]
This should now be complete. Should it also change the input to be alphabetical? Are there other fields that should adhere to this as well?

**Comment by rolesc** [comment]
Thank you, Steven! I'm not sure what you mean about the input also being alphabetical--could you clarify? As for other fields, it would be great if the UFs could also display in alphabetical order!


---

Cailin Flannery Roles (she/they)

Ph.D. Student, Northeastern University

Department of English

Project Coordinator, Homosaurus<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.homosaurus.org%2F&data=04%7C01%7Croles.c%40northeastern.edu%7C3fc4a359f3654d336a4d08d988306ae2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637690563823354916%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FJtnHV2JIU5yE7fmxFLWMPQu5aQkz%2BCX2SGW9vbgCvk%3D&reserved=0>

Special Projects, Digital Transgender Archive<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.digitaltransgenderarchive.net%2F&data=04%7C01%7Croles.c%40northeastern.edu%7C3fc4a359f3654d336a4d08d988306ae2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637690563823344924%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8wVnjQcV1wJZdhMvfhaKhW%2FlrBNXFN1eWjYRO5iJzVQ%3D&reserved=0>

________________________________

**Comment by scande3** [comment]
@rolesc -> The UFs should be alphabetical.

The other question was having the "Edit form" having the BTs, NTs, etc all alphabetical in listing based on the label over just the current display change.

**Comment by rolesc** [comment]
Gotcha! It would be great to have the Edit form in alphabetical order too, thank you!


---

Cailin Flannery Roles (she/they)

Ph.D. Student, Northeastern University

Department of English

Project Coordinator, Homosaurus<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.homosaurus.org%2F&data=04%7C01%7Croles.c%40northeastern.edu%7C3fc4a359f3654d336a4d08d988306ae2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637690563823354916%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FJtnHV2JIU5yE7fmxFLWMPQu5aQkz%2BCX2SGW9vbgCvk%3D&reserved=0>

Special Projects, Digital Transgender Archive<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.digitaltransgenderarchive.net%2F&data=04%7C01%7Croles.c%40northeastern.edu%7C3fc4a359f3654d336a4d08d988306ae2%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637690563823344924%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8wVnjQcV1wJZdhMvfhaKhW%2FlrBNXFN1eWjYRO5iJzVQ%3D&reserved=0>

________________________________

**Comment by kjrawson** [comment]
This seems like it was fully fixed. Thank you!
