### ISSUE TITLE
Update how the 040$f is set in the mapping to MARCXML

### ISSUE THREAD

**Issue by gmcharlt** [DigitalTransgenderArchive/homosaurus_site#31]
I noticed that there is a discrepancy in the code assigned to the thesaurus [by the Library of Congress](https://www.loc.gov/standards/sourcelist/subject.html) ("homoit") versus the code that shows up on the 040$f of the MARCXML authority records generated by the website ("homosaurus").

Per the [documentation of the 040 field by the Library of Congress](https://www.loc.gov/marc/authority/ad040.html), subfield $f may contain either the name of the thesaurus or the code. However, I know of at least two library software systems (Koha and Evergreen) that would expect the values in the authority 040$f and the bib 650$2 to match exactly, so I suggest considering updating the mapping to set the 040$f value to "homoit".

If you agree, I'm happy to toss a pull request your way.

**Comment by kjrawson** [comment]
@scande3 just wanted to check with you saw this comment?

**Comment by scande3** [comment]
@gmcharlt -> Apologies for the slow reply on this issue as had missed it previously. Sure if you still want to submit that pull request. Thanks!

**Comment by gmcharlt** [comment]
@scande3 Thanks! I've opened #34

**Comment by scande3** [comment]
@gmcharlt -> Thanks for the contribution! I've approved and merged it.
