### ISSUE TITLE
Add link for Threadless shop

### ISSUE THREAD

**Issue by kjrawson** [DigitalTransgenderArchive/homosaurus_site#9]
Hi, Steven.
When you have a moment, could you add the following sentence (with the hyperlink) to the homepage below the first full paragraph but before the "If you are using..." sentence? Thank you!

If you are interested in purchasing some Homosaurus swag, please visit our [online shop](https://homosaurus.threadless.com/). All proceeds are used to support the project or are donated to LGBTQ+ organizations.

**Comment by scande3** [comment]
This should be completed.

**Comment by kjrawson** [comment]
Thank you!
